name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sudo docker login --username=${{ secrets.Aliyun_Username }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.Aliyun_Password }}
        tag=${GITHUB_REF:11}
        echo "Build Tag '$tag'"
        sudo docker build ./ --file Dockerfile --tag ccmall.core:$tag
        sudo docker tag ccmall.core:$tag registry.cn-hangzhou.aliyuncs.com/harryczqp/ccmall.core:latest
        sudo docker push registry.cn-hangzhou.aliyuncs.com/harryczqp/ccmall.core:latest
