name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        sudo docker login --username=${{ secrets.Aliyun_Username }} registry.cn-hangzhou.aliyuncs.com --password=${{ secrets.Aliyun_Password }}
        sudo docker build ./ --file Dockerfile --tag ccmall.core:$(date +%s) registry.cn-hangzhou.aliyuncs.com/harryczqp/ccmall.core:$(date +%s)
        sudo docker push registry.cn-hangzhou.aliyuncs.com/harryczqp/ccmall.core:$(date +%s)
